#!/bin/sh
# Main program
# Copyright (c) 2016 Civic Knowledge. This file is licensed under the terms of the
# Revised MIT License, included in this distribution as LICENSE

exec python -mcensus_extract "$@"